/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-url-data-model.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../raml-aware/raml-aware.d.ts" />
/// <reference path="../api-view-model-transformer/api-view-model-transformer.d.ts" />

/**
 * `api-url-data-model`
 * An element to generate view model for api-url-editor and api-url-params-editor elements from AMF model
 */
declare class ApiUrlDataModel extends Polymer.Element {

  /**
   * A web API model generated by the AMF.
   * This property is required to compyte parameters properly.
   */
  webApi: string|null|undefined;

  /**
   * Name of the scope to use with `raml-aware`.
   * If this element is used with other aware elements, it updates
   * `webApi` when aware value change.
   */
  aware: string|null|undefined;

  /**
   * The `@id` property of selected endpoint and method to compute
   * data models for.
   */
  selected: string|null|undefined;

  /**
   * Computed view model for API uri parameters.
   */
  readonly apiParameters: any[]|null|undefined;

  /**
   * Computed value of API base URI.
   */
  readonly apiBaseUri: string|null|undefined;

  /**
   * Generated view model for query parameters.
   */
  readonly queryModel: any[]|null|undefined;

  /**
   * Generated view model for path parameters
   */
  readonly pathModel: object|null;

  /**
   * Computed value of full endpoint URI when selection has been made.
   */
  readonly endpointUri: string|null|undefined;

  /**
   * Selected emndponit relative path.
   */
  readonly endpointPath: string|null|undefined;

  /**
   * Clears computed base values of the API.
   */
  _resetBaseValues(): void;

  /**
   * Clears variables related to selected object.
   */
  _resetObjectValues(): void;

  /**
   * Computes basic properties when model change.
   *
   * @param model The document model
   */
  _webApiChanged(model: object|null): void;

  /**
   * Computes `apiBaseUri` property when `amfModel` change.
   *
   * @param model The `http://schema.org/WebAPI` model
   */
  _computeApiBaseUri(model: object|null): void;

  /**
   * Computes uri paramerters lsit for API base
   *
   * @param model The `http://schema.org/WebAPI` model
   */
  _computeApiUriParams(model: object|null): void;

  /**
   * Checks if a model has a type.
   *
   * @param model Model to test
   * @param type Type name
   * @returns True if model has a type.
   */
  _modelHasType(model: object|null, type: String|null): Boolean|null;

  /**
   * @param model Amf model
   * @returns Value for the model.
   */
  _getAmfValue(model: object|null): String|null|undefined;

  /**
   * Handler for the `selected` property change.
   * Computes model for URI and query parameters from selected endpoint.
   *
   * @param id The `@id` property of selected object.
   */
  _selectedChanged(id: String|null): void;

  /**
   * Computes endpoint `@id` for given `id`.
   * On a base level it subrtacts the last part after `/` which
   * is a delimiter between endpoint identifier and method name.
   *
   * @param id Object ID. Can be operation's or endpoint's ID.
   * @returns Endpoint id. It may return the same value if passed
   * id is endpoint ID.
   */
  computeEndpointId(id: String|null): String|null;

  /**
   * Finds an endpoint definition in the API.
   *
   * @param endpointId Endpoint `@id` from AMF model
   * @param api AMD model for the api. If not set, `webApi` property
   * is used.
   * @returns Definition of the endpoint.
   */
  findEndpoint(endpointId: String|null, api: object|null): object|null;

  /**
   * Finds a method definition on the list of operations for an endpoint.
   *
   * @param id ID of the operation (method)
   * @param operations List of endpoint's operations.
   * @returns Method definition.
   */
  findMethod(id: String|null, operations: Array<object|null>|null): object|null|undefined;

  /**
   * Computes endpoint full URI by combining `apiBaseUri` with `path`.
   *
   * @param path Endpoint's path
   * @returns Endpoint's full uri.
   */
  computeEndpointUri(path: String|null): String|null;

  /**
   * Sets up view model for parameters.
   *
   * @param params List of parameters from the endpoint
   * definition.
   */
  _setupPathViewModel(params: any[]|null): Promise<any>|null;

  /**
   * Produces view model for query parameters.
   *
   * @param method Method definition in the endpoint model.
   */
  _setupQueryViewModel(method: object|null): Promise<any>|null;
}

interface HTMLElementTagNameMap {
  "api-url-data-model": ApiUrlDataModel;
}
